MMDB.ServiceFaker.Web/Controllers/FakeServiceController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using MMDB.ServiceFaker.Web.Services;
using MMDB.ServiceFaker.Web.Dto;

namespace MMDB.ServiceFaker.Web.Controllers
{
    public class FakeServiceController : Controller
    {
		private readonly IServiceRepository _serviceRepository;
		
		public FakeServiceController(IServiceRepository serviceRepository)
		{
			_serviceRepository = DIHelper.VerifyParameter(serviceRepository);
		}

        public ActionResult Index()
        {
			var list = _serviceRepository.LoadFakeServiceList();
            return View(list);
        }

		public ActionResult Create()
		{
			return View();
		}

		[HttpPost]
		public ActionResult Create(string serviceName, string realEndpointRootUrl, string relativeFakeRootUrl, EnumFakeServiceResponseType enumFakeServiceResponseTypeID)
		{
			var item = _serviceRepository.CreateFakeService(serviceName, realEndpointRootUrl, relativeFakeRootUrl, enumFakeServiceResponseTypeID);
			return RedirectToAction("Details", new { id=item.ID });
		}

		public ActionResult Details(int id)
		{
			var item = _serviceRepository.GetFakeService(id);
			return View(item);
		}

		public ActionResult Edit(int id)
		{
			var item = _serviceRepository.GetFakeService(id);
			return View(item);
		}

		[HttpPost]
		public ActionResult Edit(int id, string serviceName, string realEndpointRootUrl, string relativeFakeRootUrl, EnumFakeServiceResponseType enumFakeServiceResponseTypeID)
		{
			var item = _serviceRepository.UpdateFakeService(id, serviceName, realEndpointRootUrl, relativeFakeRootUrl, enumFakeServiceResponseTypeID);
			return RedirectToAction("Details", new { id = item.ID });
		}
    }
}

MMDB.ServiceFaker.Web/Views/Shared/DisplayTemplates/Enum.cshtml
@model Enum
@MMDB.Shared.EnumHelper.GetDisplayValue(Model)

MMDB.ServiceFaker.Web/Views/Shared/DisplayTemplates/FakeService.cshtml
@model MMDB.ServiceFaker.Web.Dto.FakeService

<fieldset>
    <legend>FakeService</legend>

	<table class="table">
		<tr>
			<th>Service Name</th>
			<td>@Html.DisplayFor(model => model.ServiceName)</td>
		</tr>
		<tr>
			<th>Real Endpoint Root URL</th>
			<td>@Html.DisplayFor(model=>model.RealEndpointRootUrl)</td>
		</tr>
		<tr>
			<th>Relative Fake Root URL</th>
			<td>@Html.DisplayFor(model => model.RelativeFakeRootUrl)</td>
		</tr>
		<tr>
			<th>Response Type</th>
			<td>@Html.DisplayFor(model => model.EnumFakeServiceResponseTypeID, "Enum")</td>
		</tr>
	</table>
</fieldset>
In order to intercept these service calls, replace the URL <b>@Model.RealEndpointRootUrl/whatever</b> with <b>@Url.ContentFullPath("~/fake/" + Model.RelativeFakeRootUrl + "/whatever")</b>
<p>
    @Html.ActionLink("Edit", "Edit", new { id=Model.ID }) |
    @Html.ActionLink("Back to List", "Index")
</p>

MMDB.ServiceFaker.Web/Views/Shared/DisplayTemplates/FakeServiceList.cshtml
@model IEnumerable<MMDB.ServiceFaker.Web.Dto.FakeService>

<h2>Fake Services</h2>
<table class="table table-striped">
	<thead>
		<tr>
			<th>Service Name</th>
			<th>Real Endpoint</th>
			<th>Relative Fake Endpoint</th>
			<th>Response Type</th>
		</tr>
	</thead>
	<tbody>
		@foreach(var service in Model)
		{
			<tr>
				<td>@Html.ActionLink(service.ServiceName, "Details", "FakeService", new {id=service.ID}, null)</td>
				<td>@service.RealEndpointRootUrl</td>
				<td>@service.RelativeFakeRootUrl</td>
				<th>@MMDB.Shared.EnumHelper.GetDisplayValue(service.EnumFakeServiceResponseTypeID)</th>
				<td>@Html.ActionLink("Edit", "Edit", "FakeService", new {id=service.ID}, new {@class="btn btn-primary"})</td>
				<td>@Html.ActionLink("Delete", "Delete", "FakeService", new {id=service.ID}, new {@class="btn btn-danger"})</td>
			</tr>
		}
	</tbody>
</table>
@if(Model.Count() == 0)
{
	<em>No Services Yet</em>
}
@Html.ActionLink("Create Fake Service", "Create", "FakeService")